### ISSUE TITLE
歌曲路径输入框的bug

### ISSUE THREAD

**Issue by HiDolen** [SlimeNull/UnityAudioVisualizer#1]
在导入本地歌曲时发现程序不能进行读取。

经过调试，发现是当输入的路径过长时，Text只会截取字符串的一部分，导致路径错误。

建议是重写 MusicLoad.cs 的 LoadMusic 函数使之能输入 InputField 类型的参数，并将 Scenes 中的 InputField 直接作为参数绑定到 LoadButton 上。

**Comment by SlimeNull** [comment]
现在把 LoadMusic 函数的参数改成 InputField, 测试了一些比较长的路径, 应该没问题了.
